 server:
  port: 8081
  servlet:
      context-path: /o2oSchedu
 spring:
    aop:
        proxy-target-class: true
    datasource:
        url: jdbc:mysql://116.62.118.138:3306/alio2o_test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: ron
        password: qwer1234@11
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
 mybatis:
  mapper-locations: /mapping/*.xml
  configuration:
      mapUnderscoreToCamelCase: true


 envirDetect: dev
